### ISSUE TITLE
Swap Interface not showing

### ISSUE THREAD

**Issue by xuhcc** [liquality/liquality-launcher#1]
When I click "Open Swap interface" in tray menu, browser opens `http://localhost:5555/`, but it is not loading. There are no errors in the console:

```
$ npm start

> liquaity-launcher@0.1.3 start /.../liquality-launcher
> electron ./src/main.js
```

OS: Arch Linux
NodeJS: v11.15.0

**Comment by monokh** [comment]
Thanks for raising the issue. I can confirm that i see the same running the linux release at 0.1.3. We are investigating the issue.

In the meantime, if you are interested in running the interface directly, you can do so directly from the project: https://github.com/liquality/liquality-swap

**Comment by monokh** [comment]
The issue was that the local server was not serving on ipv4 on linux. This has now been fixed.
You can either pull the latest code or use the latest [release](https://github.com/liquality/liquality-launcher/releases/tag/v0.1.4).

Let us know if you encounter any more issues.

**Comment by xuhcc** [comment]
Thanks!
