### ISSUE TITLE
Launcher is serving an incomplete version of the swap 

### ISSUE THREAD

**Issue by gr0kchain** [liquality/liquality-launcher#2]
I just downloaded the latest Liquality Launcher version (0.2.0) for macOS, but I can't access the swap interface. In fact, when I click "Open Swap Interface", my browser open and goes to http://localhost:5555/. So far, so good. But instead of the normal swap interface, the contents of the directory is displayed (see screenshot attached).

<img width="517" alt="download (2)" src="https://user-images.githubusercontent.com/7654306/74124607-89cc2580-4bdb-11ea-9f0a-89bd1f002880.png">
<img width="636" alt="Screenshot 2020-02-10 at 07 58 51" src="https://user-images.githubusercontent.com/7654306/74124615-95b7e780-4bdb-11ea-8826-1f5d0921aa9a.png">

**Comment by monokh** [comment]
The latest UI bundle was faulty. Released v0.2.2. Should be resolved.
